# ===============================
# DATABASE POSTGRESQL (RENDER)
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d7t0lsgk1i2s73a743b0-a.virginia-postgres.render.com:5432/elearning_db_5dna?sslmode=require

spring.datasource.username=elearning_db_5dna_user
spring.datasource.password=PqWbpSMQ0K7IFTVnqMtuFaj7dLKWmaOx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# ===============================
# SERVER
# ===============================
server.address=0.0.0.0
server.port=${PORT:8080}

# ===============================
# APP
# ===============================
spring.application.name=elearning-api
# ===============================
# TIMEOUTS & FIXES
# ===============================
spring.jpa.open-in-view=false
spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.socket-timeout=5000
spring.jpa.properties.jakarta.persistence.query.timeout=5000

# ===============================
# FILE UPLOAD (\uD83D\uDD25 IMPORTANT FIX)
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# ===============================
# SWAGGER (OPENAPI)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# ===============================
# LOGGING (OPTIONNEL MAIS UTILE)
# ===============================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB